### ISSUE TITLE
data races in the OpenMP version code

### ISSUE THREAD

**Issue by chunhualiao** [TheFighters/Smith-Waterman#2]
maxPos is read in the if-condition expression. The read is not protected. 

```
    //Updates maximum score to be used as seed on backtrack
    if (max > H[*maxPos]) {
        #pragma omp critical
        *maxPos = index;
    }
```

**Comment by danielholanda** [comment]
Please submit a pull request and I will be happy to accept it.

**Comment by chunhualiao** [comment]
See https://github.com/TheFighters/Smith-Waterman/pull/3 
Thanks a lot for contributing this code to the community.

**Comment by danielholanda** [comment]
Merged! Thanks for your contribution!
